### ISSUE TITLE
TLS problem

### ISSUE THREAD

**Issue by ihr** [mephux/kolide#11]
Hi there,

I'm trying to setup a distributed osquery environment. I followed the example given in the README of this repository but from osqueryd I get "No node key returned from TLS enroll plugin" whereas from kolide side I get either nothing and once "oversized record received with length 64774". Any ideas what could be wrong ?

**Comment by ihr** [comment]
The problem was in my configuration file I used enroll_secret_env instead of enroll_secret_path

**Comment by zwass** [comment]
Glad you got it sorted!
