### ISSUE TITLE
Readme mentions kolide.io, site seems to be .co

### ISSUE THREAD

**Issue by 0xdabbad00** [mephux/kolide#14]
kolide.io doesn't seem to exist.  The site seems to be hosted at kolide.co

**Comment by tonylambiris** [comment]
I believe kolide.io is used in examples to reference local endpoints. @mephux does it make sense to setup a DNS entry for kolide.io to point to localhost?

**Comment by mephux** [comment]
@tonylambiris @0xdabbad00 yea, initially that was the reason. I should be changed to .co now tho just for more information and because they will be sponsoring and continuing development. Fixed.

**Comment by marpaia** [comment]
#37
