### ISSUE TITLE
make failing on build

### ISSUE THREAD

**Issue by burdzz** [mephux/kolide#2]
make is failing each time I try to build kolide. I am running ubuntu linux 14.04, go1.6 linux/amd64.
The commands I am running can be seen below - 
```
test@kolide-box:/opt# go get github.com/mephux/kolide
# github.com/mephux/kolide/static
src/github.com/mephux/kolide/static/static.go:14: undefined: Asset
src/github.com/mephux/kolide/static/static.go:15: undefined: AssetDir
src/github.com/mephux/kolide/static/static.go:16: undefined: AssetInfo
src/github.com/mephux/kolide/static/template.go:21: undefined: AssetDir
src/github.com/mephux/kolide/static/template.go:39: undefined: MustAsset

test@kolide-box:/opt/src/github.com/mephux/kolide# go build
# github.com/mephux/kolide/static
static/static.go:14: undefined: Asset
static/static.go:15: undefined: AssetDir
static/static.go:16: undefined: AssetInfo
static/template.go:21: undefined: AssetDir
static/template.go:39: undefined: MustAsset

test@kolide-box:/opt/src/github.com/mephux/kolide# make build
kolide
go version go1.6 linux/amd64
Go Path: /opt

shared/querycontrol/control.go:104: arg id for printf verb %d of wrong type: string
exit status 1
make: *** [lint] Error 1
```

Please let me know if I am doing anything wrong / need to include anything else to get the binary compiled.

**Comment by mephux** [comment]
@burdzz looking into it now - will let you know.

**Comment by mephux** [comment]
@burdzz pushed some readme updates and a new `make` task called `deps` this will install a few of the dev deps needed to package assets with the server. Let me know if this fixes your problem.

**Comment by burdzz** [comment]
I was able to make kolide using `make deps` then `make`. Thanks very much @mephux - can't wait to get this online.

**Comment by ukd1** [comment]
I'm still getting this today @burdzz, can you re-open?

```
$ make deps && make
Installing build deps
go get -u github.com/golang/lint/golint
go get github.com/jteeuwen/go-bindata/...
go get github.com/elazarl/go-bindata-assetfs/...
kolide
go version go1.7 darwin/amd64
Go Path: /Users/russ/go

Running go generate...
Building kolide...
# github.com/kolide/kolide/static
../github.com/kolide/kolide/static/static.go:14: undefined: Asset
../github.com/kolide/kolide/static/static.go:15: undefined: AssetDir
../github.com/kolide/kolide/static/static.go:16: undefined: AssetInfo
../github.com/kolide/kolide/static/template.go:21: undefined: AssetDir
../github.com/kolide/kolide/static/template.go:39: undefined: MustAsset
make: *** [build] Error 2
```

**Comment by groob** [comment]
@ukd1 it looks like you skipped the `go generate` step

**Comment by ukd1** [comment]
@groob I literally just solved it by changing folder...to ~/go/src/github.com/kolide/kolide and re-running...I'd cloned to ~/go/src/kolide and it doesn't work from there..

**Comment by groob** [comment]
Yes, that's a go thing. You must use the same VCS path as the project.

If you fork a go project, put it in the same namespace as the original, but change the remote to use your fork. https://golang.org/doc/code.html#Workspaces
