### ISSUE TITLE
kolide cannot start - pq: SSL not enabled 

### ISSUE THREAD

**Issue by burdzz** [mephux/kolide#3]
@mephux sorry for all the issues however no matter what I define in the configuration file / running it in dev mode I cannot get past this issue "FATAL Database Error: pq: SSL is not enabled on the server" 

```
test@kolide-box:/opt/src/github.com/mephux/kolide# ./bin/kolide --config=kolide.conf
[May 10 18:42:21]  INFO ENV: Production
[May 10 18:42:21] FATAL Database Error: pq: SSL is not enabled on the server
test@kolide-box:/opt/src/github.com/mephux/kolide# ./bin/kolide --dev --config=kolide.conf
[May 10 18:45:54]  INFO ENV: Development
[May 10 18:45:54] FATAL Database Error: pq: SSL is not enabled on the server
```
My configuration file can be found below - 
```
[database]
type = "postgres"
host = "127.0.0.1"
port = "5432"
username = "kolide"
password = "kolide"
database = "kolide"
sslmode = "disable"

[session]
name = "kolide"
type = "redis"
network = "tcp"
address = "127.0.0.1:6379"

[server]
query_timeout = "10s"
enroll_secret = "test"
production = false
debug = false
address = ":8000"
crt = "./tmp/kolide.crt"
key = "./tmp/kolide.key"
```

**Comment by mephux** [comment]
@burdzz no worries - the syntax changed a bit and i forgot to update the readme. https://github.com/mephux/kolide/blob/master/shared/kolide.toml this is usually more up to date because i use it for testing.


```toml

[database]
# postgres or sqlite
type = "postgres"
address = "127.0.0.1:5432"
username = "kolide"
password = "kolide"
database = "kolide"
ssl = "disable"
cert = ""
key = ""
```

i dropped the ssl before crt/key and renamed sslmode to just ssl

**Comment by mephux** [comment]
ops actually a lot more changed then just that - base your config off of https://github.com/mephux/kolide/blob/master/shared/kolide.toml for now - i'll update the readme tonight. thanks for reporting this.

**Comment by burdzz** [comment]
No wonder grepping for `sslmode` and `pqsslmode` Thanks so much for the updated configuration! finally have some green on my screen below!
```
INFO Starting server: https://:8000
```
Really appreciate the work!

**Comment by marpaia** [comment]
+1, this will make it easier to run the front-end for me I think, because I'm not sure how well the whole JavaScript ecosystem works on Windows #windowsproblems

**Comment by marpaia** [comment]
It would be cool if we could use docker to test running many web servers since eventually, we'll want to test what it would be like to run something like 15 kolide web servers and 3 database servers (M:S:S) to ensure that we can horizontally scale the API / ensure that all requests are stateless.

**Comment by zwass** [comment]
Docker/docker-compose (with the `scale` command) should make it relatively easy to test the scaling once we get this set up.

**Comment by terracatta** [comment]
> +1, this will make it easier to run the front-end for me I think, because I'm not sure how well the whole JavaScript ecosystem works on Windows #windowsproblems

This problem isn't solved yet by my PR, but when I get react rocking and we have webpack, I'll make sure this is turn key.

**Comment by terracatta** [comment]
> It would be cool if we could use docker to test running many web servers since eventually, we'll want to test what it would be like to run something like 15 kolide web servers and 3 database servers (M:S:S) to ensure that we can horizontally scale the API / ensure that all requests are stateless.

This will be possible with my PR.
